# Generated by Django 5.1.1 on 2024-11-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_articleelon_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korupsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('title_en', models.CharField(blank=True, max_length=250, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=250, null=True)),
                ('body', models.TextField()),
                ('body_en', models.TextField(blank=True, null=True)),
                ('body_ru', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='Photos/Yangiliklar/')),
                ('img1', models.ImageField(upload_to='Photos/Yangiliklar/')),
                ('img2', models.ImageField(upload_to='Photos/Yangiliklar/')),
                ('img3', models.ImageField(upload_to='Photos/Yangiliklar/')),
                ('video', models.CharField(max_length=500)),
                ('publish_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_time'],
            },
        ),
    ]
